services:
  postgres:
    image: postgres:15
    container_name: dsev_postgres
    restart: always
    profiles:
      - local-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: dsev
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d dsev"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dsev_be
    restart: always
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/gcs-key.json
      GCS_BUCKET: dsev_image
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SEPAY_API_KEY: ${SEPAY_API_KEY}
      SEPAY_BANK: ${SEPAY_BANK}
      SEPAY_ACCOUNT: ${SEPAY_ACCOUNT}

    volumes:
      - /home/rsa-key-20251024/dsev-476107-9d5c478f0e23.json:/app/gcs-key.json:ro
    ports:
      - "8080:8080"

volumes:
  pg_data: